name: llama-token-counter
type: gradio-space
sdk: streamlit

metadata:
  space_id: Chris4K/llama-token-counter
  original_url: https://huggingface.co/spaces/Chris4K/llama-token-counter

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"
